version: '3.7'

services:
  react-frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports:
        - "3000:3000"
      container_name: react-frontend-container
      restart: unless-stopped