# values.yaml

# Define values for the my-flask-python-app deployment
flaskPythonApp:
  image: flask-python-app:latest
  port: 8082

# Define values for the gin-golang-app deployment
ginGolangApp:
  image: gin-golang-app:latest
  port: 8081

# Define values for the postgres deployment
postgres:
  image: postgres:latest
  imagePullPolicy: IfNotPresent
  port: 5432
  storageSize: 1Gi
  replicas: 1
  password: root
  username: root
  databse: mydatabase

# Define values for the react-frontend deployment
reactFrontend:
  port: 80
  targetPort: 80
  containerPort: 80
  image: react-frontend:latest

# Define values for the spring-boot-app deployment
springBootApp:
  image: spring-boot-app:latest
  port: 8080
