apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-flask-python-app
  template:
    metadata:
      labels:
        app: my-flask-python-app

    spec:
      containers:
      - name: my-flask-python-app
        image:  my-flask-python-app:latest
        imagePullPolicy: IfNotPresent  # or Never
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: my-flask-python-app
spec:
  selector:
    app: my-flask-python-app
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
