apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-gin-golang-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-gin-golang-app
  template:
    metadata:
      labels:
        app: my-gin-golang-app
    spec:

      containers:
      - name: my-gin-golang-app
        image: my-gin-golang-app:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: my-gin-golang-app
spec:
  selector:
    app: my-gin-golang-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
