apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # adjust the storage size as needed
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgresdb-pvc
      containers:
      - name: postgresdb
        image: postgresdb:latest
        imagePullPolicy: IfNotPresent  # or Never
        env:
        - name: POSTGRES_USER
          value: "root"
        - name: POSTGRES_PASSWORD
          value: "root"
        - name: POSTGRES_DB
          value: "mydatabase"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data  # adjust the mount path as needed
---
apiVersion: v1
kind: Service
metadata:
  name: postgresdb-service
spec:
  selector:
    app: postgresdb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
