apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
      - name: react-frontend
        image: react-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: FLASK_BACKEND_URL
          value: "http://my-flask-python-app:8082"  # Adjust port as needed
        - name: GIN_BACKEND_URL
          value: "http://my-gin-golang-app:8081"    # Adjust port as needed
        - name: SPRING_BACKEND_URL
          value: "http://my-spring-boot-app:8080"   # Adjust port as needed
