apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-flask-python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-flask-python-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-flask-python-app
    spec:
      containers:
      - name: {{ .Release.Name }}-flask-python-app
        image: {{ .Values.flaskPythonApp.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.flaskPythonApp.port }}