# templates/flask-python-app-deployment.yaml

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-flask-python-app
spec:
  selector:
    app: {{ .Release.Name }}-flask-python-app
  ports:
    - protocol: TCP
      port: {{ .Values.flaskPythonApp.port }}
      targetPort: {{ .Values.flaskPythonApp.port }}
