apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gin-golang-app
spec:
  selector:
    app: {{ .Release.Name }}-gin-golang-app
  ports:
    - protocol: TCP
      port: {{ .Values.ginGolangApp.port }}
      targetPort: {{ .Values.ginGolangApp.targetPort }}
