apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres
spec:
  replicas: {{ .Values.postgres.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgres
    spec:
      containers:
      - name: {{ .Release.Name }}-postgres
        image: {{ .Values.postgres.image }}
        imagePullPolicy: {{ .Values.postgres.imagePullPolicy }}
       
        env:
          - name: POSTGRES_PASSWORD
            value: "{{ .Values.postgres.password }}"
          - name: POSTGRES_USERNAME
            value: "{{ .Values.postgres.username }}"
          - name: POSTGRES_DB
            value: "{{ .Values.postgres.database }}"
        ports:
        - containerPort: {{ .Values.postgres.port }}
