apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-react-frontend
spec:
  type: LoadBalancer
  selector:
    app: {{ .Release.Name }}-react-frontend  # This line selects pods with the label app=<release-name>-react-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.reactFrontend.port }}
      targetPort: {{ .Values.reactFrontend.targetPort }}
