apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-spring-boot-app
spec:
  selector:
    app: {{ .Release.Name }}-spring-boot-app
  ports:
    - protocol: TCP
      port: {{ .Values.springBootApp.port }}
      targetPort: {{ .Values.springBootApp.port }}
